"use strict";
const fbkt = require('../../../fbkt');

const arnie = [
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNmNNNNMMMMMNmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddNNNmNMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmdNNNNNNNNNMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmddNNNddmmNNMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmddmmyshdmNMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmdddo+ohmNMMMMMMMMMMMNNNMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmdds/:ohmMMMMMMMMMMMNNNNMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmds/:shdNMMMMMMMMMMMNNNMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmds+ymNNMMMMMMMMMMMMMMNMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmsddNMMMMNNMMMMMMMMMNNNMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmosydNMNmydMMMMMMMMMMNNMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmdh/:ohmmy/sNMMMMMMMMNNNNNMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmdy/:oyydssmMMMMMMMMNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmsssyo+ysydMMMMMMMNNNNMNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmyyhs/oo+smMMMMMMMNNNMMNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmhydh/hyhmNMMMMMMMMNMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhdyMmsymMMMMMMMMMMMMMMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhydNdhmNMMMMMMMMMMMMMMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhshdmmNMMMMMMMMMMMMMMNmmmmmmmmmmNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmhydNMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMNNmmmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdshNMMMMMMMMMMMMMMMMMNMMMMMNNMMMMMMMMMNNMMMMMMNmmmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmy+yhmMMMMMMMMMMMMMMMMMMmmMmNMNMMMMMMMmMMMMMMMMMNmmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd+oohMMMNNNMMMMMMMMMMMNdmNdhdmNMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmshmNNNNMMNNNNMMMMMMMMMNdyymNMMMMNMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmNNNNNMNNNMMMNNNMMMMMmsshmNMMMMNNMMMMMMMMMMMMMMMMMNmmmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMmNNNNMMMMMMMmmNNNNMMmsydmNMMMMNNMMMMMMMMMMMMMMMMMMMMNmmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMNNNMMMMMMMMMMNmmNNNmMMhshmNMMMMNNNMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmm",
	"mmmmmmmmmmmmmmmmmmmmmmmmmmmNMMMMNNMMMMMMMMMMNNNNNNNNNmdhhdmNMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmmmN",
	"mmmmmmmmmmmmmmmNNmmmmmmmmNMMMMNNMMMMMMMMMNmdmNNNMMMNNhshmmNMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMmmmmmmNNN",
	"mmmmmmmmmmmmmmmNNmmdmmNMNMMMNMMMMMMMMMNmdmmNNNNMMMMNysydmNNMMMMMMNNmmmNNMMMMMMMMMMMMMMMMMMMNmmmmNNNN",
	"mmmmmmmmmmmmmmmNNmmmmNMMMMMMMMMMMMMMMNmdddmNMMNMMMNyosddmNNNNMMMNNNmmNNNNNNNMMMMMMMMMMMMMMMMNmmNNNNN",
	"mmmmmmmmmmmmmmmNmmdmNNMMMNMMMMMMMMMMmdmmmmNMMMMMMMdosdhddmmNNMMNNNNNNNmmmNNMMMMMMMMMMMMMMMMMMNNNNNNN",
	"mmmmmmmmmmmmmmdymNNmNMMMNNMMMMMMMMNNNmmmmNMMMMMMMMsydddmNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMNNNNNN",
	"mmmmmmmmmmmmmmdhmmmNMMMNmMMMMMMMMNNmNmddmmNMMNNNNNmmNNNMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNN",
	"mmmmmmmmmmmmmmNmhmNMMMNmmMMMMMMMNmmddmmNNNNMNNNNNNMMNNMMNMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNN",
	"mmmmmmmmmmmmmmmdmMMMMNmmmMMMMMMMNhymNNNMMMMMMNNNNNNNNNMNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN",
	"mmmmmmmmmmmmmmdNMMMMMNNmmMMMMMMMmddNNNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmmmMMMMMMMMNNdmmmNNMNmmmNNNNMMMMNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmmNMMMMMMMMMMhhmNMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmMMMMMMMMMNNNdmNNNNMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmMMMMMMMNmmmNNNNMMNMMMMMMNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmMMMMMMMNNNMMNMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNN",
	"mmmmmmmmmmmmMMMMMMMMMMNNdNMMMMMMMMMMMMMNNNNMMNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMNNNN",
	"mmmmmmmmmmmmMMMMMMMMNNmmmmNNMMMMMMMNNNNNNNNMNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNN",
	"mmmmmmmmmmmNMMMMNmmmNNNNMmmNMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNN",
	"mmmmmmmNNNmMMMNMmmNNMMMMMNmNMMMMMMMMNNNMNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNN",
	"mmmNNNNNNmdMMMNh/ymMMMNNNNmNMMMMNMMMMMMMNNNdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNN",
	"mNNNNNNNNdNMMMmoomNNMMMNNNmMMMMMMNNMNMMMNMMNmdmNMMMMMMMMMMMMMNdNMMMMMMMMMMMMMMMMNNNNMMNmNNNNNNNNNNNN",
	"MMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
].join('\n');
module.exports = ()=>{
	const port = process.env.PORT || fbkt().config.getConfigValue('port') || 20831;
	
	fbkt().app.listen(port, function () {
		console.log('...');
		// console.log(arnie);
		console.log('...');
		console.log('come with me if you want to live');
		console.log('...');
		console.log('functioN_Bucket is intently listening on port '+port);
	});
};